version: 2.1

orbs:
  python: circleci/python@0.2.1
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Unit Tests
          command: make test-unit
      - run:
          name: Integration Tests
          command: make test-integration
      - store_test_results:
          path: ./test-results
  quality-gate-sonar:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Install Coverage
          command: pip install coverage
      - run:
          name: Test Coverage
          command: make test-coverage
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build-and-test
      - quality-gate-sonar:
          context: SonarCloud
