version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: pip install .
          name: Install Package
      - run:
          command: python -m unittest discover
          name: Test
      - run:
          command: python -m unittest discover -p integration*.py
          name: Integration Test

workflows:
  main:
    jobs:
      - build-and-test
