version: 2.1

orbs:
  python: circleci/python@0.2.1
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: make test-unit
          name: Unit Tests
      - run:
          command: make test-integration
          name: Integration Tests
      - store_test_results:
          path: ./test-results
  quality-gate-sonar:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build-and-test
      - quality-gate-sonar:
        context: SonarCloud
